### ISSUE TITLE
Update and merge into Box2D?

### ISSUE THREAD

**Issue by Asmageddon** [mtsamis/box2d-optimized#11]
Found this via the benchmarks page, and honestly, it looks really good. Is there any reason for keeping it as a separate project instead of merging the optimisations into the base library?

**Comment by mtsamis** [comment]
The reason is that Box2D in general doesn't accept code contibutions for features or enchancements. It is mentioned in the README (See [Contributing](https://github.com/erincatto/box2d?tab=readme-ov-file#contributing)).

My goal was to explore ideas that may end up affecting the original project and also highlight the potential performance gap. That's why the focus was on the technical writeup and benchmarks rather than the implementation.

Note that since then Erin Catto has started working on Box2D v3 ([erincatto/box2c](https://github.com/erincatto/box2c)), which is vastly more optimizied that the original and also surpasses my work in most ways (including substantial solver improvements). So this project is now obsolete in many ways.
